// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otzsmypzbnzrirejidaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90enNteXB6Ym56cmlyZWppZGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NzQ0MDEsImV4cCI6MjA1NDA1MDQwMX0.hIP_rT0Zwbrur-Y6dwOgVjsrQLOiNT9Q4V0w_qjQyCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);