// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clroxysgbxtkrutsqjis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNscm94eXNnYnh0a3J1dHNxamlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzE4MzYsImV4cCI6MjA2MTQ0NzgzNn0.Pp_wKuJr9vAsSIqJr0SFyXREj-v0sxL1WSwIdi9fVcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);